In [8]:
import numpy as np

In [39]:
a = np.arange(6)

In [40]:
a2 = a[np.newaxis, :]

In [41]:
a2.shape

(1, 6)

In [42]:
a = np.array([1,2,3,4,5,6])

In [43]:
print (a[0])

1


In [44]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [45]:
print (a[1])

[5 6 7 8]


In [46]:
a = np.arange(15).reshape(3, 5)

In [47]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
b = np.arange(20).reshape(4, 5)

In [49]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [50]:
c = np.arange(100).reshape(10, 10)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [51]:
c = np.arange(121).reshape(11,11)
c

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [52]:
c = np.arange(100)

In [53]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [54]:
c = np.arange(100).reshape(20,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [55]:
c.shape

(20, 5)

In [56]:
c.ndim

2

In [57]:
c.dtype

dtype('int64')

In [58]:
c.dtype.name

'int64'

In [59]:
c.size

100

In [60]:
c.itemsize

8

In [62]:
type(c)

numpy.ndarray

In [63]:
type(a)

numpy.ndarray

In [64]:
d = np.array([2,3,4])

In [65]:
type(d)

numpy.ndarray

In [71]:
d = np.array([2,3,4])

In [72]:
d

array([2, 3, 4])

In [73]:
type(d)

numpy.ndarray

In [74]:
d.dtype

dtype('int64')

In [75]:
e = np.array([1.2,3.2,5.1])
e

array([1.2, 3.2, 5.1])

In [76]:
d.dtype

dtype('int64')

In [77]:
e.dtype

dtype('float64')

In [80]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [81]:
f = np.array([(1.5,2,3),(4,5,6)])
f

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [82]:
g = np.array([[1,2],[2,3]], dtype=complex)
g

array([[1.+0.j, 2.+0.j],
       [2.+0.j, 3.+0.j]])

In [84]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [85]:
np.ones((8,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [87]:
np.empty((1,2))

array([[0., 0.]])

In [96]:
np.ones((3,5), dtype=np.int16)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [97]:
np.empty((3,6), dtype=np.int16)

array([[16288,  3799, 22087,     0,     0,     0],
       [    0,     0, 14882, 12578, 13877, 13623],
       [14641, 11570, 25909, 25187, 13357, 12599]], dtype=int16)

In [98]:
np.empty((3,6), dtype=np.float)

array([[ 4.68686448e-310,  0.00000000e+000,  2.14632833e+054,
         6.91283025e-310,  6.91281429e-310,  1.03906869e+153],
       [ 6.91283025e-310,  6.91281429e-310,  1.32360900e-080,
         6.91283025e-310,  6.91281429e-310, -2.65570625e+187],
       [ 6.91283025e-310,  6.91281429e-310, -3.75826366e-133,
         6.91283025e-310,  6.91281429e-310,  6.91282586e-310]])

In [99]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [100]:
np.arange(2,30)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [111]:
np.arange(10,20,30)

array([10])

In [112]:
np.arange(1)

array([0])

In [113]:
np.arange(60,5)

array([], dtype=int64)

In [119]:
np.arange(60,18000,360000)

array([60])

In [120]:
np.arange(0.2,4)

array([0.2, 1.2, 2.2, 3.2])

In [121]:
np.arange(0.2,4,40)

array([0.2])

In [122]:
np.arange(0.2,4)

array([0.2, 1.2, 2.2, 3.2])

In [123]:
np.arange(0.2,40)

array([ 0.2,  1.2,  2.2,  3.2,  4.2,  5.2,  6.2,  7.2,  8.2,  9.2, 10.2,
       11.2, 12.2, 13.2, 14.2, 15.2, 16.2, 17.2, 18.2, 19.2, 20.2, 21.2,
       22.2, 23.2, 24.2, 25.2, 26.2, 27.2, 28.2, 29.2, 30.2, 31.2, 32.2,
       33.2, 34.2, 35.2, 36.2, 37.2, 38.2, 39.2])

In [124]:
from numpy import pi

In [125]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [126]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [127]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [128]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [129]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [130]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

In [133]:
np.linspace(0,9,10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [134]:
np.linspace(0,9,11)

array([0. , 0.9, 1.8, 2.7, 3.6, 4.5, 5.4, 6.3, 7.2, 8.1, 9. ])

In [139]:
np.linspace(0,90,10)

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [141]:
np.linspace(0,90,19)

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60.,
       65., 70., 75., 80., 85., 90.])

In [146]:
np.linspace(2,5)

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [149]:
a = np.arange(50)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [153]:
a = np.arange(50).reshape(2,25)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]]


In [154]:
a = np.arange(50).reshape(5,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [156]:
a = np.arange(50).reshape(2,5,5)
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [159]:
a = np.arange(60).reshape(2,5,2,3)
print(a)

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]

  [[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]

  [[24 25 26]
   [27 28 29]]]


 [[[30 31 32]
   [33 34 35]]

  [[36 37 38]
   [39 40 41]]

  [[42 43 44]
   [45 46 47]]

  [[48 49 50]
   [51 52 53]]

  [[54 55 56]
   [57 58 59]]]]


In [160]:
a = np.arange(60).reshape(4,5,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]]


In [162]:
a = np.arange(60).reshape(3,4,5)
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [163]:
a = np.arange(60).reshape(1,5,12)
print(a)

[[[ 0  1  2  3  4  5  6  7  8  9 10 11]
  [12 13 14 15 16 17 18 19 20 21 22 23]
  [24 25 26 27 28 29 30 31 32 33 34 35]
  [36 37 38 39 40 41 42 43 44 45 46 47]
  [48 49 50 51 52 53 54 55 56 57 58 59]]]


In [164]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [165]:
np.arange(5000000)

array([      0,       1,       2, ..., 4999997, 4999998, 4999999])

In [168]:
np.arange(2,100)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [175]:
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [176]:
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [182]:
a=np.array([20,30,40,50,60])
b=np.arange(5)
b

array([0, 1, 2, 3, 4])

In [184]:
c=a-b
c

array([20, 29, 38, 47, 56])

In [188]:
b*2

array([0, 2, 4, 6, 8])

In [189]:
b=np.arange(5)

In [191]:
b**2

array([ 0,  1,  4,  9, 16])

In [192]:
b**3

array([ 0,  1,  8, 27, 64])

In [193]:
b**5

array([   0,    1,   32,  243, 1024])

In [194]:
b**1/2

array([0. , 0.5, 1. , 1.5, 2. ])

In [195]:
b**0.3

array([0.        , 1.        , 1.23114441, 1.39038917, 1.51571657])

In [196]:
np.sin(a)

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485, -0.30481062])

In [197]:
50*np.cos(a)

array([ 20.40410309,   7.71257249, -33.34690308,  48.24830142,
       -47.62064902])

In [198]:
np.cos(a)

array([ 0.40808206,  0.15425145, -0.66693806,  0.96496603, -0.95241298])

In [201]:
np.sin(a)

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485, -0.30481062])

In [204]:
1/np.sin(a)

array([ 1.09535594, -1.01211335,  1.34207803, -3.81134086, -3.28072557])

In [206]:
1/np.cos(b)

array([ 1.        ,  1.85081572, -2.40299796, -1.01010867, -1.52988566])